In [33]:
import pandas as pd 
df=pd.read_csv(r'C:\Users\Dell\OneDrive\Desktop\data analyst\assignment.py\train.csv')

In [34]:
df.isna().sum() # its isnull is used to count the null value count/ sum of null value

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [35]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [36]:
df.drop(columns=["Row ID","Country"],inplace=True)

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9800 non-null   str
 1   Order Date     9800 non-null   str
 2   Ship Date      9800 non-null   str
 3   Ship Mode      9800 non-null   str
 4   Customer ID    9800 non-null   str
 5   Customer Name  9800 non-null   str
 6   Segment        9800 non-null   str
 7   City           9800 non-null   str
 8   State          9800 non-null   str
 9   Postal Code    9789 non-null   float64
 10  Region         9800 non-null   str
 11  Product ID     9800 non-null   str
 12  Category       9800 non-null   str
 13  Sub-Category   9800 non-null   str
 14  Product Name   9800 non-null   str
 15  Sales          9800 non-null   float64
dtypes: float64(2), str(14)
memory usage: 2.8 MB

In [38]:
df["Order Date"]=pd.to_datetime(df["Order Date"] , dayfirst=True)
df["Ship Date"]=pd.to_datetime(df["Ship Date"] , dayfirst=True)
print(df[["Order Date", "Ship Date"]].head())

  Order Date  Ship Date
0 2017-11-08 2017-11-11
1 2017-11-08 2017-11-11
2 2017-06-12 2017-06-16
3 2016-10-11 2016-10-18
4 2016-10-11 2016-10-18

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9800 non-null   str
 1   Order Date     9800 non-null   datetime64[us]
 2   Ship Date      9800 non-null   datetime64[us]
 3   Ship Mode      9800 non-null   str
 4   Customer ID    9800 non-null   str
 5   Customer Name  9800 non-null   str
 6   Segment        9800 non-null   str
 7   City           9800 non-null   str
 8   State          9800 non-null   str
 9   Postal Code    9789 non-null   float64
 10  Region         9800 non-null   str
 11  Product ID     9800 non-null   str
 12  Category       9800 non-null   str
 13  Sub-Category   9800 non-null   str
 14  Product Name   9800 non-null   str
 15  Sales          9800 non-null   float64
dtypes: datetime64[us](2), float64(2), str(12)
memory usage: 2.6 MB

In [40]:
df["Postal Code"]=df['Postal Code'].fillna(0).astype(int).astype(str).str.zfill(5)

In [41]:
df.isna().sum()

Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [42]:
df.nunique()

Order ID         4922
Order Date       1230
Ship Date        1326
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
City              529
State              49
Postal Code       627
Region              4
Product ID       1861
Category            3
Sub-Category       17
Product Name     1849
Sales            5757
dtype: int64

In [43]:
df['Ship_Days'] = (df['Ship Date'] - df['Order Date']).dt.days
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Ship_Days
0,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3
2,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4
3,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,7

In [44]:
df['Order_Year'] = df['Order Date'].dt.year
df['Order_Month'] = df['Order Date'].dt.month

In [45]:
df.head(15)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Ship_Days,Order_Year,Order_Month
0,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3,2017,11
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,2017,11
2,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,2017,6
3,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7,2016,10
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,7,2016,10
5,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,5,2015,6
6,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,5,2015,6
7,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,5,2015,6
8,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,5,2015,6
9,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,2015,6
10,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,5,2015,6
11,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,90032,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,5,2015,6
12,CA-2018-114412,2018-04-15,2018-04-20,Standard Class,AA-10480,Andrew Allen,Consumer,Concord,North Carolina,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520,5,2018,4
13,CA-2017-161389,2017-12-05,2017-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,Seattle,Washington,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760,5,2017,12
14,US-2016-118983,2016-11-22,2016-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,Fort Worth,Texas,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,4,2016,11

In [46]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9800 non-null   str
 1   Order Date     9800 non-null   datetime64[us]
 2   Ship Date      9800 non-null   datetime64[us]
 3   Ship Mode      9800 non-null   str
 4   Customer ID    9800 non-null   str
 5   Customer Name  9800 non-null   str
 6   Segment        9800 non-null   str
 7   City           9800 non-null   str
 8   State          9800 non-null   str
 9   Postal Code    9800 non-null   str
 10  Region         9800 non-null   str
 11  Product ID     9800 non-null   str
 12  Category       9800 non-null   str
 13  Sub-Category   9800 non-null   str
 14  Product Name   9800 non-null   str
 15  Sales          9800 non-null   float64
 16  Ship_Days      9800 non-null   int64
 17  Order_Year     9800 non-null   int32
 18  Order_Month    9800 non-null   int32
dtypes: datetime64[us](2), float64(1), int32(2), int64(1), str(13)
memory usage: 2.8 MB

In [47]:
import os
import mysql.connector
import pandas as pd
from dotenv import load_dotenv


load_dotenv()


try:
    db = mysql.connector.connect(
        host=os.getenv("DB_HOST"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        database=os.getenv("DB_NAME")
    )
    print("Successfully connected to the database!")
    
 
    query = "SELECT * FROM sales_data"
    df = pd.read_sql(query, db)
    
   
    print(df.head())

except mysql.connector.Error as err:
    print(f"Error: {err}")

finally:
    if 'db' in locals() and db.is_connected():
        db.close()
        print("MySQL connection is closed.")

Successfully connected to the database!

C:\Users\Dell\AppData\Local\Temp\ipykernel_5304\1560104649.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db)

         Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0  CA-2017-152156 2017-11-08 2017-11-11    Second Class    CG-12520
1  CA-2017-152156 2017-11-08 2017-11-11    Second Class    CG-12520
2  CA-2017-138688 2017-06-12 2017-06-16    Second Class    DV-13045
3  US-2016-108966 2016-10-11 2016-10-18  Standard Class    SO-20335
4  US-2016-108966 2016-10-11 2016-10-18  Standard Class    SO-20335

     Customer Name    Segment             City       State Postal Code Region  \
0      Claire Gute   Consumer        Henderson    Kentucky       42420  South
1      Claire Gute   Consumer        Henderson    Kentucky       42420  South
2  Darrin Van Huff  Corporate      Los Angeles  California       90036   West
3   Sean O'Donnell   Consumer  Fort Lauderdale     Florida       33311  South
4   Sean O'Donnell   Consumer  Fort Lauderdale     Florida       33311  South

        Product ID         Category Sub-Category  \
0  FUR-BO-10001798        Furniture    Bookcases
1  FUR-CH-10000454        Furniture       Chairs
2  OFF-LA-10000240  Office Supplies       Labels
3  FUR-TA-10000577        Furniture       Tables
4  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Ship_Days  \
0                  Bush Somerset Collection Bookcase  261.9600          3
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400          3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200          4
3      Bretford CR4500 Series Slim Rectangular Table  957.5775          7
4                     Eldon Fold 'N Roll Cart System   22.3680          7

   Order_Year  Order_Month
0        2017           11
1        2017           11
2        2017            6
3        2016           10
4        2016           10
MySQL connection is closed.